version: '3'
services:
  taggit:
    profiles: ["all"]
    container_name: 'taggit'
    image: 'taggit:latest'
    ports:
      - '127.0.0.1:8080:8080'
    depends_on:
      - postgres
    networks:
      - default
    environment:
      - DATABASE_URL=jdbc:postgresql://postgres:5432/taggit
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=
      - GITHUB_CLIENT_ID=
      - GITHUB_CLIENT_SECRET=
      - UI_URL=http://localhost:8081
      - TURN_OFF_SESSION_TOKEN_CHECK=
      - JWT_SIGNING_KEY=
      - GITHUB_TOKEN_ENCRYPTION_KEY=
      - ACTIVE_PROFILE=local
  postgres:
    profiles: ["all", "infra"]
    container_name: 'postgres'
    image: 'postgres:latest'
    ports:
      - '127.0.0.1:5432:5432'
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - 'pgdata:/var/lib/postgresql/data/'
    networks:
      - default

volumes:
  pgdata:
