spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/taggit}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:postgres}
  output:
    ansi:
      enabled: always
  flyway:
    enabled: true
  profiles:
    active: ${ACTIVE_PROFILE:local}
    default: local
  jpa:
    properties:
      hibernate:
        types:
          print:
            banner: false

external:
  githubUserName: ${GITHUB_USER_NAME:}
  githubAccessToken: ${GITHUB_ACCESS_TOKEN:}
  appPassword: ${APP_PASSWORD:}

logging:
  level:
    root: info
    io.shiveenp.taggit: debug
