spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/taggit}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:}
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: ${GITHUB_CLIENT_ID}
            clientSecret: ${GITHUB_CLIENT_SECRET}
  output:
    ansi:
      enabled: always
  flyway:
    enabled: true
  redis:
    host: localhost
    port: 6379
  session:
    store-type: redis

external:
  uiUrl: http://localhost:8081
  turnOffSessionTokenCheck: true

logging:
  level:
    root: info
    com.shiveenp.taggit: debug
